services:
  postgres:
    image: postgres:15-alpine
    container_name: orion-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: orion_v
      POSTGRES_USER: orion_user
      POSTGRES_PASSWORD: orion_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - orion-network

  redis:
    image: redis:7-alpine
    container_name: orion-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - orion-network

volumes:
  postgres_data:
  redis_data:

networks:
  orion-network:
    driver: bridge
